//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarsRents = new HashSet<CarsRent>();
        }
    
        public int id { get; set; }
        public string CarModel { get; set; }
        public int CurrentDistance { get; set; }
        public byte[] Image { get; set; }
        public bool ProperForRent { get; set; }
        public bool FreeForRent { get; set; }
        public int CarNumber { get; set; }
        public string Branch { get; set; }
    
        public virtual Branch Branch1 { get; set; }
        public virtual CarType CarType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarsRent> CarsRents { get; set; }
    }
}
