//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarsRent
    {
        public int id { get; set; }
        public System.DateTime StartRent { get; set; }
        public System.DateTime FinishRent { get; set; }
        public System.DateTime RealFinishRent { get; set; }
        public int NumUser { get; set; }
        public int NumCar { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual User User { get; set; }
    }
}
